resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource

gate-source: &gate-source
  git:
    uri: git@github.com:iverberk/concourse-gates.git
    private_key: |
      DUMMY
    branch: master

resources:
  - name: a-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: a

  - name: b-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: b

  - name: auto-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: autogate

jobs:
  - name: push-a
    plan:
    - task: push-a
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: "3.6"
        outputs:
        - name: gen
        run:
          path: sh
          dir: gen
          args:
          - -exc
          - |
            echo "dummy" > "123456789012.v0.9.0"
    - put: a-gate
      params:
        item_file: "gen/123456789012.v0.9.0"

  - name: push-b
    plan:
    - task: push-b
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: "3.6"
        outputs:
        - name: gen
        run:
          path: sh
          dir: gen
          args:
          - -exc
          - |
            echo "dummy" > "210987654321.v0.9.0"
    - put: b-gate
      params:
        item_file: "gen/210987654321.v0.9.0"

  - name: push-autogate
    plan:
    - task: push-autogate
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
            tag: "3.6"
        outputs:
        - name: gen
        run:
          path: sh
          dir: gen
          args:
          - -exc
          - |
            echo "a/123456789012.v0.9.0" >> "accounts.v0.9.0.autoclose"
            echo "b/210987654321.v0.9.0" >> "accounts.v0.9.0.autoclose"
    - put: auto-gate
      params:
        item_file: gen/accounts.v0.9.0.autoclose

  - name: autoclose-autogate
    plan:
      - aggregate:
        - get: a-gate
          trigger: true
        - get: b-gate
          trigger: true
      - put: auto-gate
        params:
          update_autoclose: true

  - name: echo
    plan:
      - get: auto-gate
        trigger: true
      - task: echo
        config:
          inputs:
            - name: auto-gate
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
              tag: "3.6"
          run:
            path: sh
            args:
            - -exc
            - |
              ls -la

              if [ ! -f "auto-gate/passed" ]; then
                echo "No passed file"
                exit 0
              fi

              cat auto-gate/passed
